# Generated by Django 4.1.2 on 2023-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_myexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myexperience',
            old_name='icon_image',
            new_name='about_avatar',
        ),
        migrations.RenameField(
            model_name='myexperience',
            old_name='service_description',
            new_name='role_info',
        ),
        migrations.RemoveField(
            model_name='myexperience',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='myexperience',
            name='shadow_icon',
        ),
        migrations.AddField(
            model_name='myexperience',
            name='company_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='role',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='myexperience',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
